Update contacts-sync
Added some minor and crude retry functionality for when data to/from google is munged, incidental "service unavailable" errors pop up, etc. 
limited to 5 retries, any more than that and it's probably something more serious like a UID mismatch, or a contact accessed/updated since the script run started.
add rety and force exit before updating local index in case it fails.


adding-new-account isn't working in new version, when set, errors "AttributeError: 'UserContacts' object has no attribute 'email'"